name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  pull_request:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language:
          - typescript
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Analyze vulnerabilities
        run: npm audit

      - name: Lint and format code
        run: npm run eslint

      - name: Tests
        run: npm run tests --if-present

  push_to_develop:
    runs-on: ubuntu-latest
    needs: pull_request

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Deploy to staging
        run: |
          echo "Deploying to staging"
          # comandos para fazer deploy da aplicação em um ambiente de staging
